### PR TITLE
nav-child should be made site-agnostic

### LINKED ISSUE #74: nav-child should be made site-agnostic
This section of nav-child should be changed:
https://github.com/MITLibraries/MITLibraries-child/blob/master/inc/nav-child.php#L10-L12

Specifically, there shouldn't be code in a theme that references a specific site (or sites). Is it possible that this would be done via widgets, or via theme option?

(edit: updating link)

### PR DESCRIPTION
**Pull request by PBruk**
Tagging @matt-bernhardt for code-review: this branch removes site-specific references, instead checking if menu has been assigned and splits postHead.php into 2 specific concerns: the header and navbar. Resolves #74.

### CODE REVIEW

**Comment by matt-bernhardt** [comment]
I need to ponder this change for a bit. I _think_ I understand the change you're proposing, but want to make sure its the direction we want to head.

**Comment by PBruk** [comment]
totally makes sense...it's no small switcheroo that i am proposing.

**Comment by matt-bernhardt** [comment]
After reviewing this, and the current state of the Child theme, I have a few questions for either @PBruk or @frrrances:

One of the big changes here is a shift in the approach to the header and nav elements. Currently, a page template calls one file, `inc/postHead.php`, which then renders both the header image (directly in `inc/postHead.php` and the navbar (in a sub-template, `inc/nav-child.php`). This PR proposes to have individual pages each call both partials. My questions about this are:
- How often do sites using the Child theme need one but not both pieces of content? Do sites ever need the masthead image and not the navbar, or use the navbar but not the masthead image?
- If it is ever the case that a site does not need both elements, how are content editors controlling whether the desired element appears / does not appear?
- How often do we anticipate rolling new sites out, and how much of a risk is it to have navigation hinge on a specifically-named menu existing? The PR looks like it automagically loads the `child-nav` menu on the referenced pages, provided such menu exists. Is that likely to trip up site builders? On a related note, are the site builders likely to only be part of the UX team, or might they be distributed around the organization?

I'm mildly concerned about hanging the navigation display off a specifically-named menu, but I'm slightly more concerned (not to say opposed) to requiring that each page template replace the same structure to conditionally load both elements:

```
<?php

get_template_part( 'inc/header-child' );

// Checks to see if menu has not been assigned.
if ( !has_nav_menu( 'child-nav' ) ) {

    wp_nav_menu( array(
        'theme_location' => 'child-nav',
        'fallback_cb' => false,
    ) );

    echo '' ;

} else {

    // Otherwise, if menu has been assigned, get navbar. -->
    get_template_part( 'inc/nav', 'child' );

}
```

Repeating code like this on N page templates (where N is currently 5, and may get larger over time) seems like a recipe for inconsistently-applied changes down the road. Might it be better to have the if/else structure contained within `inc/nav-child.php`, so the call from the pages would just be:

```
get_template_part( 'inc/header-child' );
get_template_part( 'inc/nav', 'child' );
```

?

**Comment by matt-bernhardt** [comment]
Almost a year later, I think it is time to close this and clean up our backlog of work. Philip, if you get a zombie notification for this, my apologies :-)

**Pull request closed without merging**
