### PR TITLE
The category breadcrumb is showing specific posts

### LINKED ISSUE #97: The category breadcrumb is showing specific posts
breadcrumbs

### PR DESCRIPTION
**Pull request by PBruk**
Tagging @frrrances for code-review: create breadcrumb template for categories and add to category templates. Resolves #97.

### CODE REVIEW

**Comment by frrrances** [comment]
i'm not familiar enough with WP to do this review. @matt-bernhardt can you review?

**Comment by matt-bernhardt** [comment]
This is close, but not quite right. I'll adjust.

**Comment by matt-bernhardt** [comment]
Kind of odd to review my own commit, but what I changed was:

a) swapping from `esc_html__()` to `esc_url()` in the breadcrumb partial. It doesn't make sense to use a translating function in this context, as URLs aren't subject to translation. Also, the WP codex gives the example of using `esc_url()` - https://codex.wordpress.org/Function_Reference/home_url

b) fixing code indenting. This required a second "Oops" commit because I missed what level CodeClimate would want (guessed it would want two tabs, it actually wanted one). I tried squashing this into one commit, but ran into problems - I think because I'm appending onto some work of Phillip's.

At any rate, this should now be ready to merge.

**Comment by frrrances** [comment]
green checks look good! 👍

**Pull request merged**
