### PR TITLE
Adds default image, implements theme partial for hero image

### PR DESCRIPTION
**Pull request by matt-bernhardt**
Asking for code review from:
- [x] @frrrances 
- [x] @PBruk 

This branch adds a default image to the theme for use as hero images, and also abstracts out the template for the hero image to a new partial.

### CODE REVIEW

**Comment by frrrances** [comment]
nice! 👍

**Comment by matt-bernhardt** [comment]
This is also meant to implement https://trello.com/c/udGUiE39/21-create-fallback-hero-image-for-all-ct-sites

**Comment by frrrances** [comment]
lgtm. 👍

**Comment by PBruk** [comment]
Code reviewed and wowed by: super clever improvement of my initial PR. Really LGTM. +1

**Pull request merged**
