### PR TITLE
Exhibit updates to use excerpt field

### PR DESCRIPTION
**Pull request by hllavina**
addresses #118 
uses excerpt field to display on exhibits summary

### CODE REVIEW

**Comment by frrrances** [comment]
Looks good! This is an add-on so feel free to push back, but would it be possible to have the cards use the beginning of the main content area if the excerpt isn't set?

**Comment by hllavina** [comment]
Yes, I have updated the field to use the content area if the excerpt field is not populated. i updated dev

**Comment by frrrances** [comment]
Nice! I just noticed one more thing... can we limit the excerpt to 500 characters max?

**Comment by hllavina** [comment]
We could cut off at 500 characters but I'd suggest considering leaving it up to the content editors to judge length.  the character count  include counts of  html  formatting  and links as well as text since the field is not stripping them out,a character count may be long but the resulting text would be short if it includes paragraph tags and links and images

**Comment by frrrances** [comment]
Makes sense!

**Review by frrrances — DISMISSED** [review]
Looks good! 👍

**Review by matt-bernhardt — COMMENTED** [review]
The intent of the change looks good - can you take a look at the CodeClimate report on this PR (which should be at https://codeclimate.com/github/MITLibraries/MITLibraries-child/pull/124 ) and look over the whitespace flags that are being raised? There's a few tab-indent flags as well, but I'm less concerned about that while the page as a whole is such a huge mess.

**Comment by hllavina** [comment]
Yikes I misread the checks , should all be fixed now

**Review by matt-bernhardt — DISMISSED** [review]
Looks good!

**Comment by frrrances** [comment]
This might be a good PR to try a rebase cleanup on the commit history :)

**Review by matt-bernhardt — APPROVED** [review]
Looks good - well done.

**Review by frrrances — APPROVED** [review]
Nice! 👍

**Pull request merged**
