### PR TITLE
Cleans recently added violations

### PR DESCRIPTION
**Pull request by matt-bernhardt**
The recent upgrade to PHPCS 2.9 has introduced a few new tests, which the theme is currently failing. This branch will correct them.

### CODE REVIEW

**Comment by hllavina** [comment]
The pagination issue that codeclimate found I am addressing, the lack of pagination will be going away for exhibits, not sure how you would like to handle it for this pr?

**Comment by matt-bernhardt** [comment]
Oh, cool - if you're taking care of that, I can temporarily pass it in CodeClimate this time.

I've got one more commit to make on this branch, and then it'll be formally ready for review.

**Review by hllavina — DISMISSED** [review]
Looks good to me

**Comment by matt-bernhardt** [comment]
Dagnabit, it seems that my squashing has triggered the need for a new code review.

**Review by hllavina — APPROVED** [review]
ok looks good

**Pull request merged**
